spring:
  application:
    name: orderservice
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      profile: local
      label: main
    stream:
      defaultBinder: kafka
      function:
        bindings:
          orderCreatedEvent-out-0: order-topic
      bindings:
        orderCreatedEvent-out-0:
          destination: order-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  



